package shared.definitions;

public enum MoveType
{
    SEND_CHAT, ROLL_NUMBER, ROB_PLAYER, FINISH_TURN, BUY_DEV_CARD, YEAR_OF_PLENTY, ROAD_BUILDING, SOLDIER, MONOPOLY,
    MONUMENT, BUILD_ROAD, BUILD_SETTLEMENT, BUILD_CITY, OFFER_TRADE, ACCEPT_TRADE, MARITIME_TRADE, DISCARD_CARDS;
}
