CREATE TABLE IF NOT EXISTS "Game"( GameID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE , Model BLOB NOT NULL , CurrentCommandNo INTEGER NOT NULL DEFAULT 0, Name VARCHAR )

CREATE TABLE IF NOT EXISTS "User"( UserID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE , Name VARCHAR NOT NULL UNIQUE , Password VARCHAR NOT NULL )

CREATE TABLE IF NOT EXISTS "Command"(SequenceNo INTEGER NOT NULL , Command BLOB NOT NULL, GameID INTEGER NOT NULL, FOREIGN KEY(GameID) References Game(GameID));

CREATE TABLE IF NOT EXISTS "GameRelation"(GameID INTEGER NOT NULL, UserID INTEGER NOT NULL, FOREIGN KEY(GameID) References Game(GameID) )